/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksDailyForecastRouteImport } from './routes/hooks.daily-forecast'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppForecastForecastIdRouteImport } from './routes/_app.forecast.$forecastId'
import { Route as ApiPublicMapsEuropePressureLatestDotsvgRouteImport } from './routes/api/public/maps/europe-pressure-latest[.]svg'
import { Route as ApiPublicHooksGeneratePressureMapRouteImport } from './routes/api/public/hooks/generate-pressure-map'
import { Route as ApiPublicDebugR2CacheRouteImport } from './routes/api/public/debug/r2-cache'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksDailyForecastRoute = HooksDailyForecastRouteImport.update({
  id: '/hooks/daily-forecast',
  path: '/hooks/daily-forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastForecastIdRoute = AppForecastForecastIdRouteImport.update({
  id: '/forecast/$forecastId',
  path: '/forecast/$forecastId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicMapsEuropePressureLatestDotsvgRoute =
  ApiPublicMapsEuropePressureLatestDotsvgRouteImport.update({
    id: '/api/public/maps/europe-pressure-latest.svg',
    path: '/api/public/maps/europe-pressure-latest.svg',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGeneratePressureMapRoute =
  ApiPublicHooksGeneratePressureMapRouteImport.update({
    id: '/api/public/hooks/generate-pressure-map',
    path: '/api/public/hooks/generate-pressure-map',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDebugR2CacheRoute = ApiPublicDebugR2CacheRouteImport.update({
  id: '/api/public/debug/r2-cache',
  path: '/api/public/debug/r2-cache',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/hooks/daily-forecast': typeof HooksDailyForecastRoute
  '/forecast/$forecastId': typeof AppForecastForecastIdRoute
  '/api/public/debug/r2-cache': typeof ApiPublicDebugR2CacheRoute
  '/api/public/hooks/generate-pressure-map': typeof ApiPublicHooksGeneratePressureMapRoute
  '/api/public/maps/europe-pressure-latest.svg': typeof ApiPublicMapsEuropePressureLatestDotsvgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/hooks/daily-forecast': typeof HooksDailyForecastRoute
  '/forecast/$forecastId': typeof AppForecastForecastIdRoute
  '/api/public/debug/r2-cache': typeof ApiPublicDebugR2CacheRoute
  '/api/public/hooks/generate-pressure-map': typeof ApiPublicHooksGeneratePressureMapRoute
  '/api/public/maps/europe-pressure-latest.svg': typeof ApiPublicMapsEuropePressureLatestDotsvgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/hooks/daily-forecast': typeof HooksDailyForecastRoute
  '/_app/forecast/$forecastId': typeof AppForecastForecastIdRoute
  '/api/public/debug/r2-cache': typeof ApiPublicDebugR2CacheRoute
  '/api/public/hooks/generate-pressure-map': typeof ApiPublicHooksGeneratePressureMapRoute
  '/api/public/maps/europe-pressure-latest.svg': typeof ApiPublicMapsEuropePressureLatestDotsvgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/hooks/daily-forecast'
    | '/forecast/$forecastId'
    | '/api/public/debug/r2-cache'
    | '/api/public/hooks/generate-pressure-map'
    | '/api/public/maps/europe-pressure-latest.svg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/hooks/daily-forecast'
    | '/forecast/$forecastId'
    | '/api/public/debug/r2-cache'
    | '/api/public/hooks/generate-pressure-map'
    | '/api/public/maps/europe-pressure-latest.svg'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/settings'
    | '/hooks/daily-forecast'
    | '/_app/forecast/$forecastId'
    | '/api/public/debug/r2-cache'
    | '/api/public/hooks/generate-pressure-map'
    | '/api/public/maps/europe-pressure-latest.svg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  HooksDailyForecastRoute: typeof HooksDailyForecastRoute
  ApiPublicDebugR2CacheRoute: typeof ApiPublicDebugR2CacheRoute
  ApiPublicHooksGeneratePressureMapRoute: typeof ApiPublicHooksGeneratePressureMapRoute
  ApiPublicMapsEuropePressureLatestDotsvgRoute: typeof ApiPublicMapsEuropePressureLatestDotsvgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/daily-forecast': {
      id: '/hooks/daily-forecast'
      path: '/hooks/daily-forecast'
      fullPath: '/hooks/daily-forecast'
      preLoaderRoute: typeof HooksDailyForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast/$forecastId': {
      id: '/_app/forecast/$forecastId'
      path: '/forecast/$forecastId'
      fullPath: '/forecast/$forecastId'
      preLoaderRoute: typeof AppForecastForecastIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/maps/europe-pressure-latest.svg': {
      id: '/api/public/maps/europe-pressure-latest.svg'
      path: '/api/public/maps/europe-pressure-latest.svg'
      fullPath: '/api/public/maps/europe-pressure-latest.svg'
      preLoaderRoute: typeof ApiPublicMapsEuropePressureLatestDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-pressure-map': {
      id: '/api/public/hooks/generate-pressure-map'
      path: '/api/public/hooks/generate-pressure-map'
      fullPath: '/api/public/hooks/generate-pressure-map'
      preLoaderRoute: typeof ApiPublicHooksGeneratePressureMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/r2-cache': {
      id: '/api/public/debug/r2-cache'
      path: '/api/public/debug/r2-cache'
      fullPath: '/api/public/debug/r2-cache'
      preLoaderRoute: typeof ApiPublicDebugR2CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppForecastForecastIdRoute: typeof AppForecastForecastIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppForecastForecastIdRoute: AppForecastForecastIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  HooksDailyForecastRoute: HooksDailyForecastRoute,
  ApiPublicDebugR2CacheRoute: ApiPublicDebugR2CacheRoute,
  ApiPublicHooksGeneratePressureMapRoute:
    ApiPublicHooksGeneratePressureMapRoute,
  ApiPublicMapsEuropePressureLatestDotsvgRoute:
    ApiPublicMapsEuropePressureLatestDotsvgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
